apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: <TEST-NAME>
  namespace: <NAMESPACE>
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - args:
                - |-
                  python3.11 -u "run.py"
              command:
                - /bin/bash
                - '-c'
                - '--'
              image: 'quay.io/michaelclifford/test-train:latest'
              name: pytorch
              resources: {}
  runPolicy:
    suspend: false
